main: chatlog.main.main
name: Chatlog
version: 1.0.0
author: Simonsator
 
commands:
  chatlog:
    desciption: Hiermit wird ein Chatlog von einem Spieler erstellt und in eine Datenbank geschrieben
    usage: /<Kommando> [name des Spielers]
  rp:
    desciption: Hiermit wird ein Chatlog von einem Spieler erstellt und in eine Datenbank geschrieben
    usage: /<Kommando> [name des Spielers]
  report:
    desciption: Hiermit wird ein Chatlog von einem Spieler erstellt und in eine Datenbank geschrieben
    usage: /<Kommando> [name des Spielers]
  cl:
    desciption: Hiermit wird ein Chatlog von einem Spieler erstellt und in eine Datenbank geschrieben
    usage: /<Kommando> [name des Spielers]